[package]
name = "esp-idf-svc"
version = "0.46.2"
authors = ["Ivan Markov <ivan.markov@gmail.com>"]
edition = "2018"
resolver = "2"
categories = ["embedded", "hardware-support"]
keywords = ["embedded", "svc", "idf", "esp-idf", "esp32"]
description = "Implementation of the embedded-svc traits for ESP-IDF (Espressif's IoT Development Framework)"
repository = "https://github.com/esp-rs/esp-idf-svc"
license = "MIT OR Apache-2.0"
readme = "README.md"
links = "esp_idf_svc"
build = "build.rs"
documentation = "https://esp-rs.github.io/esp-idf-svc/"
rust-version = "1.71"

[patch.crates-io]
embedded-svc = { git = "https://github.com/esp-rs/embedded-svc" }
esp-idf-hal = { git = "https://github.com/esp-rs/esp-idf-hal" }
esp-idf-sys = { git = "https://github.com/esp-rs/esp-idf-sys" }

[features]
default = ["std", "native", "binstart"]

std = ["alloc", "log/std", "esp-idf-hal/std", "embedded-svc/std"]
alloc = ["esp-idf-hal/alloc", "embedded-svc/alloc"]
nightly = ["embedded-svc/nightly", "esp-idf-hal/nightly"]
experimental = ["embedded-svc/experimental"]
embassy-time-driver = ["embassy-time"]
embassy-time-isr-queue = ["embassy-sync", "embassy-time", "embassy-sync"]

# Propagated esp-idf-hal features
embassy-sync = ["esp-idf-hal/embassy-sync", "dep:embassy-sync"]
critical-section = ["esp-idf-hal/critical-section"]
edge-executor = ["esp-idf-hal/edge-executor"]
# The next are propagated from esp-idf-sys via esp-idf-hal
native = ["esp-idf-hal/native"]
pio = ["esp-idf-hal/pio"]
alloc_handler = ["esp-idf-hal/alloc_handler"]
panic_handler = ["esp-idf-hal/panic_handler"]
binstart = ["esp-idf-hal/binstart"]
libstart = ["esp-idf-hal/libstart"]

[dependencies]
heapless = { version = "0.7", default-features = false }
num_enum = { version = "0.7", default-features = false }
enumset = { version = "1", default-features = false }
log = { version = "0.4", default-features = false }
uncased = "0.9.7"
embedded-svc = { version = "0.25", default-features = false }
esp-idf-hal = { version = "0.41", default-features = false, features = ["esp-idf-sys"] }
embassy-sync = { version = "0.2", optional = true }
embassy-time = { version = "0.1.3", optional = true, features = ["tick-hz-1_000_000"] }
embassy-futures = "0.1"
memchr = "2.5.0"

[build-dependencies]
embuild = "0.31.3"

[dev-dependencies]
anyhow = "1"
esp-idf-sys = { version = "0.33", features = ["native", "binstart"] }
futures = "0.3"
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
postcard = "1"

[[example]]
name = "http_request"

[[example]]
name = "wifi"

[[example]]
name = "wifi_async"

[[example]]
name = "json_post_handler"

[[example]]
name = "ws_guessing_game"
